[build-system]
requires = ["maturin>=1.7.8"]
build-backend = "maturin"

[package]
name = "COXave"
version = "1.0.0"
description = "Encoding/Decoding of codings"
authors = ["Stanislav Mikhailov <xavetar@proton.me>"]
